# Generated by Django 5.1.7 on 2025-11-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Bloga',
        ),
    ]
