# Generated by Django 5.1.7 on 2025-12-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog_delete_bloga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
