# Generated by Django 5.1.7 on 2026-01-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthhistory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='health_history_photos/'),
        ),
    ]
