# Generated by Django 5.1.7 on 2026-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_healthhistory_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthhistory',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload any image from your computer', null=True, upload_to='health_history_photos/'),
        ),
    ]
