# Generated by Django 5.1.7 on 2026-01-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wellness/posts/'),
        ),
    ]
