# Generated by Django 5.1.7 on 2026-01-14 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_wellnesspost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wellness.wellnesscomment'),
        ),
    ]
