# Generated by Django 5.1.7 on 2025-10-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('provider', 'Data Provider'), ('analyst', 'Analyst'), ('admin', 'Admin')], default='member', max_length=20),
        ),
    ]
