# Generated by Django 5.1.7 on 2025-12-18 21:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_profile_pic_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('general_medicine', 'General Medicine'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('obstetrics', 'Obstetrics'), ('general_surgery', 'General Surgery'), ('neurosurgery', 'Neurosurgery'), ('cardiac_surgery', 'Cardiac Surgery'), ('plastic_surgery', 'Plastic Surgery'), ('urology', 'Urology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology'), ('nephrology', 'Nephrology'), ('rheumatology', 'Rheumatology'), ('hematology', 'Hematology'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('dentistry', 'Dentistry'), ('psychology', 'Psychology'), ('physiotherapy', 'Physiotherapy'), ('rehabilitation', 'Rehabilitation Medicine'), ('emergency_medicine', 'Emergency Medicine'), ('critical_care', 'Critical Care'), ('fertility_specialist', 'Fertility Specialist'), ('neonatology', 'Neonatology'), ('public_health', 'Public Health'), ('occupational_health', 'Occupational Health'), ('sports_medicine', 'Sports Medicine')], max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='specialization',
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.ManyToManyField(blank=True, help_text='Only for doctors', to='accounts.specialization'),
        ),
    ]
