# Generated by Django 5.1.7 on 2025-12-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_specialization_customuser_token_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token_id',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
