# Generated by Django 5.1.7 on 2026-01-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_about_me_customuser_degrees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/doctor.jpg', null=True, upload_to='profiles/'),
        ),
    ]
