# Generated by Django 5.1.7 on 2025-12-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='temporary', unique=True),
            preserve_default=False,
        ),
    ]
