# Generated by Django 5.1.7 on 2025-12-25 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'location', 'date', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='doctorlocation',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorlocation',
            name='days',
            field=models.CharField(help_text='Sun,Tue,Thu', max_length=100),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
    ]
